name: Build android artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm test

      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Dependencies
        run: npm install

      - name: Decode Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/NiceSportMatch-key.keystore

      - name: Create local.properties
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > android/local.properties

      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_CONTENT }}" | base64 --decode > android/app/google-services.json

      - name: Verify Keystore Location
        run: |
          echo "Checking current directory..."
          pwd
          echo "Searching for NiceSportMatch-key.keystore..."
          find . -name "NiceSportMatch-key.keystore"
          if [ -f "android/app/NiceSportMatch-key.keystore" ]; then
            echo "✅ Keystore found in android/app/"
          else
            echo "❌ Keystore NOT found in expected path"
            exit 1
          fi

      - name: Build Release Bundle (AAB & APK)
        run: |
          cd android
          ./gradlew assembleRelease bundleRelease \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/android/app/NiceSportMatch-key.keystore \
            -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"

      - name: Upload AAB & APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NiceSportMatch-AAB
          path: |
            android/app/build/outputs/bundle/release/app-release.aab
            android/app/build/outputs/apk/release/app-release.apk
          retention-days: 7

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: 'testers' # Match your Firebase group name
          file: android/app/build/outputs/apk/release/app-release.apk
